version: "3.8"

services:
  warp-terminal:
    build:
      context: ./docker/warp-terminal
      args:
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    image: warp-terminal:1.0.0
    container_name: warp-terminal
    user: warpuser
    restart: unless-stopped
    environment:
      - AUTH_METHOD=${AUTH_METHOD:-keyring}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_REPO=${GITHUB_REPO}
      - GPG_KEY=${GPG_KEY}
      - GPG_KEY_ID=${GPG_KEY_ID}
      - PROJECT_PATH=${PROJECT_PATH}
      - USER_UID=${USER_UID:-1000}
      - USER_GID=${USER_GID:-1000}
    volumes:
      - ${PROJECT_PATH:-./}:/home/warpuser/project:rw
      - ${HOME}/.gitconfig:/home/warpuser/.gitconfig:ro
      - ${HOME}/.gnupg:/home/warpuser/.gnupg:rw
    cpus: "0.4"
    mem_limit: 512M
    networks:
      - web

  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--providers.docker=true"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesresolvers.le.acme.email=admin@vector-weight.click"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/letsencrypt:/letsencrypt
      - ./traefik:/etc/traefik/dynamic:ro
    networks:
      - web

