[http.middlewares.simpleAuth.basicAuth]
  usersFile = "/run/secrets/traefik-users"

[http.routers.warp-router]
  rule = "Host(\"vector-weight.click\")"
  service = "warp-terminal"

[http.services.warp-terminal.loadBalancer]
  servers = [{ url = "http://warp-terminal:7681" }]

[tls]

[tls.options]
  [tls.options.default]
    minVersion = "VersionTLS12"
